Fix - onExit & onSuccess
quan-to/connect-web-embedded pull request #4
Opened 2020-03-24 21:14 UTC by Arthuzuga

# Objective

the aim of this PR is to fix a bug caused when existing multi iFrames at the same time and postMessage doesn't know how to handle its events.

2020-03-24 22:21 UTC, nic requested changes

2020-03-24 22:21 UTC, nic commented on src/index.ts
> + handleMessage(event) {
This method is not being used. What's the idea behind adding it to this PR?

2020-03-24 23:38 UTC, nic requested changes

2020-03-24 23:38 UTC, nic commented on src/index.ts
> +   const ct = document.querySelector("#connect-embedded");
```suggestion
   const ct = document.querySelector("#connnect-embedded-81100062243781");
```

2020-03-24 23:38 UTC, nic commented on src/index.ts
> +   const ct = document.querySelector("#connect-embedded");
```suggestion
   const ct = document.querySelector("#connnect-embedded-81100062243781");
```

2020-03-25 16:07 UTC, nic approved these changes

2020-03-25 18:30 UTC, gmoura approved these changes
![](https://media.giphy.com/media/5nsiFjdgylfK3csZ5T/giphy.gif)

2020-03-25 18:42 UTC, merged